# Generated by Django 3.0.8 on 2020-07-11 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200711_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuser',
            name='follow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='response_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
